### ISSUE TITLE
tintAdjustmentMode is not inherited for controller

### ISSUE THREAD

**Issue by Igor-Palaguta** [goodpatch/PKAlertController#12]
First of all thank you for this library it is great, better than all other suggested

If I set tintAdjustmentMode for application window to Normal, controller where alert is presented anyway becomes dimmed, as you set Automatic adjustment mode in code

**Comment by roothybrid7** [comment]
Hi, I'm grad you like it. 
I add a option for tintAdjustmentMode.

**Comment by roothybrid7** [comment]
https://github.com/goodpatch/PKAlertController/releases/tag/0.5.0

@Igor-Palaguta 
I added an tintAdjustmentMode option for controller when alert is presented.
Try it out.

**Comment by Igor-Palaguta** [comment]
Thanks, it works if tintAdjustmentMode specified for configuration
