### ISSUE TITLE
How to change Title and Message color of PKAlert and handle OK default button 

### ISSUE THREAD

**Issue by arbnori45** [goodpatch/PKAlertController#3]
hello can you help me change text color of title and message of Alert ? also there is always a OK button how to handle it, or how to remove completly or replace with my custom action buttons.

**Comment by roothybrid7** [comment]
Hi arbnori45,

There is no way to change the color now. But if you use a custom view, it will be changed.
https://github.com/goodpatch/PKAlertController#custom-view

Action button can be changed. It using the constructor other than `PKAlertViewContoller#simpleAlertControllerWithConfigurationBlock:`, you may need to add your custom action buttons.
https://github.com/goodpatch/PKAlertController#pkalertviewcontroller
