### ISSUE TITLE
Can I communicate will PKAlert Custom View ?

### ISSUE THREAD

**Issue by arbnori45** [goodpatch/PKAlertController#4]
hello, can you explain me how to communicate with my custom view, to change label values from code, or do something else, because with this way on insantiating nib file as you explained in this tutorial I can't communicate ! So please explain how to initialize my custom view in pkalert in that way that i can manipulate with values ?

**Comment by roothybrid7** [comment]
Hi,
You should add some properties or methods to your custom view and call `UIView#setNeedsLayout` after changed label values.
