### ISSUE TITLE
looking for solution for reloading contraints

### ISSUE THREAD

**Issue by arbnori45** [goodpatch/PKAlertController#6]
hello, im looking to reload contraints in real time on pkalert, i have a custom uiview for pkalert, and inside that uiview I have an UIImageView, when image will inserted the alert i need to be resized, or alert to create their scrollview, I understanded that uiscrollview is created just in the beginning when estimating all heights of subviews. so i want to create that scroll view when image is inserted inside uiview. Is there a way to reload view, to recreate constraints in real time ?!

**Comment by roothybrid7** [comment]
You should call layoutIfNeeded of your custom view.
